import { describe, expect, it } from "vitest";
import type { SceneNode } from "../catalog";
import { sanitizeScene } from "../persistence";
import { generateLuau } from "../scene";
import { generateServerLuau } from "../server-luau";
import { remoteEventButtons } from "../remote-events";
import { composeScene } from "./composer";
import { defaultBlocksFor, type GuiDesignSpec } from "./spec";

const spec = (screenType: GuiDesignSpec["screenType"], extra: Partial<GuiDesignSpec> = {}): GuiDesignSpec => ({
  screenType,
  blocks: defaultBlocksFor(screenType),
  ...extra,
});

const ALL_SCREENS: GuiDesignSpec["screenType"][] = [
  "main-menu",
  "shop",
  "inventory",
  "hud",
  "daily-rewards",
  "settings",
];

// Invariants every composed scene must satisfy — mirrors the editor contract.
function checkInvariants(scene: SceneNode[]) {
  expect(scene.length).toBeGreaterThan(3);
  expect(scene.length).toBeLessThanOrEqual(150);
  // Exactly one root ScreenGui.
  const roots = scene.filter((n) => n.cls === "ScreenGui" && !n.parentId);
  expect(roots).toHaveLength(1);
  // Unique ids, all parentIds resolve, no cycles (sanitize repairs would
  // rewrite the array, so compare identity to prove none were needed).
  const ids = new Set(scene.map((n) => n.id));
  expect(ids.size).toBe(scene.length);
  for (const node of scene) {
    if (node.parentId) expect(ids.has(node.parentId)).toBe(true);
  }
  // Semantic names: no node keeps the raw class-name default ("Frame").
  for (const node of scene) {
    expect(node.name).not.toBe("Frame");
    expect(node.name).not.toBe("TextLabel");
    expect(node.name).not.toBe("TextButton");
  }
  // Only whitelisted action types with valid targets.
  for (const node of scene) {
    const action = node.action;
    if (!action) continue;
    expect(["show", "hide", "toggle", "hideGui", "remoteEvent", "teleport"]).toContain(
      action.type
    );
    const targetId = "targetId" in action ? action.targetId : undefined;
    if (targetId) {
      expect(ids.has(targetId)).toBe(true);
      const target = scene.find((n) => n.id === targetId);
      expect(["Frame", "ScrollingFrame"]).toContain(target?.cls);
    }
    if (action.type === "remoteEvent") {
      expect(action.eventName).toMatch(/^[A-Za-z0-9_]+$/);
    }
  }
  // Scale-based geometry only (responsive requirement): positions and sizes
  // are scale values; offset fields are unused by the composer.
  for (const node of scene) {
    expect(node.pos.x).toBeGreaterThanOrEqual(0);
    expect(node.pos.x).toBeLessThanOrEqual(1);
    expect(node.size.x).toBeGreaterThan(0);
    expect(node.size.x).toBeLessThanOrEqual(1);
    expect(node.posOffset).toBeUndefined();
    expect(node.sizeOffset).toBeUndefined();
  }
}

// sanitizeScene rebuilds nodes with its own key order, so compare a
// key-sorted canonical form instead of raw JSON strings.
const canonical = (value: unknown): string =>
  JSON.stringify(sortKeys(value));
function sortKeys(value: unknown): unknown {
  if (Array.isArray(value)) return value.map(sortKeys);
  if (value && typeof value === "object") {
    return Object.fromEntries(
      Object.entries(value as Record<string, unknown>)
        .sort(([a], [b]) => a.localeCompare(b))
        .map(([k, v]) => [k, sortKeys(v)])
    );
  }
  return value;
}

describe("composeScene", () => {
  it("is deterministic — identical spec, byte-identical scene", () => {
    for (const screenType of ALL_SCREENS) {
      const a = composeScene(spec(screenType));
      const b = composeScene(spec(screenType));
      expect(JSON.stringify(a)).toBe(JSON.stringify(b));
    }
  });

  it.each(ALL_SCREENS)("builds valid invariants for %s", (screenType) => {
    const scene = composeScene(spec(screenType));
    checkInvariants(scene);
  });

  it("round-trips through sanitizeScene unchanged", () => {
    for (const screenType of ALL_SCREENS) {
      const scene = composeScene(spec(screenType));
      const sanitized = sanitizeScene(JSON.parse(JSON.stringify(scene)));
      expect(sanitized).not.toBeNull();
      // sanitize normalizes nothing the composer emits: identical content
      // (modulo its own property ordering).
      expect(canonical(sanitized)).toBe(canonical(scene));
    }
  });

  it("exports to client and server Luau for every screen type", () => {
    for (const screenType of ALL_SCREENS) {
      const scene = composeScene(spec(screenType));
      const client = generateLuau(scene);
      expect(client).toContain("-- Generated by Roblox GUI Maker");
      expect(client).toContain("Instance.new");
      const remotes = remoteEventButtons(scene);
      const server = generateServerLuau(scene);
      if (server) {
        expect(server).toContain("ServerScriptService");
        for (const button of remotes) {
          expect(server).toContain(`"${button.action.eventName}"`);
        }
      }
    }
  });

  it("wires main-menu play/settings/shop through existing actions only", () => {
    const scene = composeScene({
      screenType: "main-menu",
      blocks: [
        {
          type: "menu-buttons",
          items: [
            { label: "PLAY", intent: "play" },
            { label: "SHOP", intent: "shop" },
            { label: "SETTINGS", intent: "settings" },
            { label: "CREDITS", intent: "credits" },
          ],
        },
      ],
    });
    const buttons = scene.filter((n) => n.cls === "TextButton");
    const byName = (text: string) =>
      buttons.find((b) => b.text?.toUpperCase() === text);

    expect(byName("PLAY")?.action).toEqual({ type: "hideGui" });
    const shopAction = byName("SHOP")?.action;
    expect(shopAction?.type).toBe("show");
    const settingsAction = byName("SETTINGS")?.action;
    expect(settingsAction?.type).toBe("show");
    // The show targets are hidden panels that a Close button can hide again.
    for (const action of [shopAction, settingsAction]) {
      if (action && "targetId" in action && action.targetId) {
        const panel = scene.find((n) => n.id === action.targetId);
        expect(panel?.initialVisible).toBe(false);
        const closer = buttons.find(
          (b) => b.action?.type === "hide" && b.action.targetId === action.targetId
        );
        expect(closer).toBeDefined();
      }
    }
    expect(byName("CREDITS")?.action).toBeUndefined();
    checkInvariants(scene);
  });

  it("emits whitelisted RemoteEvents for shop purchases and reward claims", () => {
    const shop = composeScene({
      screenType: "shop",
      blocks: [
        {
          type: "game-pass-grid",
          passes: [
            { name: "VIP PASS", price: "399 R$" },
            { name: "2X COINS", price: "249 R$" },
          ],
        },
      ],
    });
    const remotes = remoteEventButtons(shop).map((b) => b.action);
    expect(remotes).toEqual([
      { type: "remoteEvent", eventName: "PurchaseGamePass", argument: "vip-pass" },
      { type: "remoteEvent", eventName: "PurchaseGamePass", argument: "2x-coins" },
    ]);
    const server = generateServerLuau(shop);
    expect(server).toContain('if action == "vip-pass" then');
    expect(server).toContain('elseif action == "2x-coins" then');

    const rewards = composeScene({
      screenType: "daily-rewards",
      blocks: [{ type: "reward-calendar", days: 7 }],
    });
    const claim = remoteEventButtons(rewards).map((b) => b.action);
    expect(claim).toEqual([
      { type: "remoteEvent", eventName: "ClaimDailyReward", argument: "day-4" },
    ]);
  });

  it("respects requested counts (skills, slots, days) within caps", () => {
    const hud = composeScene({
      screenType: "hud",
      blocks: [
        { type: "stat-bar", stat: "health" },
        { type: "stat-bar", stat: "stamina" },
        { type: "skill-bar", slots: 4 },
        { type: "ultimate-meter" },
        { type: "currency-display", currencies: ["Coins", "Gems"] },
      ],
    });
    checkInvariants(hud);
    expect(hud.filter((n) => n.name.startsWith("Skill")).length).toBeGreaterThanOrEqual(4);
    expect(hud.some((n) => n.name === "HealthBarFill")).toBe(true);
    expect(hud.some((n) => n.name === "StaminaBarFill")).toBe(true);
    expect(hud.some((n) => n.name === "UltimateFill")).toBe(true);

    const inventory = composeScene({
      screenType: "inventory",
      blocks: [{ type: "item-grid", count: 20 }, { type: "item-details" }],
    });
    checkInvariants(inventory);
    expect(inventory.filter((n) => /^Slot\d+$/.test(n.name)).length).toBe(20);

    const rewards = composeScene({
      screenType: "daily-rewards",
      blocks: [{ type: "reward-calendar", days: 14 }],
    });
    checkInvariants(rewards);
    expect(rewards.filter((n) => /^Day\d+$/.test(n.name)).length).toBe(14);
  });

  it("recolors through the mood palette while keeping decorative colors", () => {
    const base = composeScene(spec("main-menu"));
    const cute = composeScene({ ...spec("main-menu"), mood: "cute" });
    const primaryBase = base.find((n) => n.color === "#00a2ff");
    expect(primaryBase).toBeDefined();
    // Cute remaps the primary slot; the decorated button follows the palette.
    const cuteButton = cute.find((n) => n.name === "playBtn");
    expect(cuteButton?.color).toBe("#ff5c8a");

    const custom = composeScene({
      ...spec("main-menu"),
      primaryColor: "#123456",
    });
    const customButton = custom.find((n) => n.name === "playBtn");
    expect(customButton?.color).toBe("#123456");
  });

  it("uses the spec title when provided", () => {
    const scene = composeScene({ ...spec("main-menu"), title: "DOOM REAPER" });
    expect(scene.find((n) => n.name === "Title")?.text).toBe("DOOM REAPER");
  });
});
